return {
  require 'plugins.autopairs',
  require 'plugins.comment',
  require 'plugins.conform',
  require 'plugins.debug',
  require 'plugins.fd',
  require 'plugins.gitsigns',
  require 'plugins.indent_line',
  require 'plugins.lint',
  require 'plugins.mason',
  require 'plugins.mini',
  require 'plugins.neo-tree',
  require 'plugins.nvim-cmd',
  require 'plugins.oil',
  -- require 'plugins.otter',
  require 'plugins.rosepine',
  require 'plugins.telescope',
  require 'plugins.todocomments',
  require 'plugins.transparent',
  require 'plugins.treesitter',
  require 'plugins.vim-sleuth',
  require 'plugins.which-key',
}
