local map = function(mode, lhs, rhs, opts)
  opts = opts or {}
  vim.keymap.set(mode, lhs, rhs, opts)
end

map("n", "<Esc>", "<cmd>nohlsearch<CR>")
map("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
map("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
map("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
map("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })
map("v", "<leader>y", '"+y', { desc = "Yank selection to system clipboard" })
map("n", "<leader>yy", '"+yy', { desc = "Yank lilne to system clipboard" })
map("n", "<leader>do", function()
  vim.diagnostic.open_float()
end, { desc = "Floating [D]iagnostic [O]pen" })
map("n", "[d", function()
  vim.diagnostic.jump({ count = -1, float = false })
end, { desc = "Go to previous [D]iagnostic message" })
map("n", "]d", function()
  vim.diagnostic.jump({ count = 1, float = false })
end, { desc = "Go to next [D]iagnostic message" })
map("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
map("n", "<leader>Q", vim.lsp.buf.code_action, { desc = "Apply [Q]uickfix" })
map("n", "<leader>rn", vim.lsp.buf.rename)
map("n", "gD", vim.lsp.buf.declaration, { desc = "[G]oto [D]eclaration" })
map("n", "K", function()
  vim.lsp.buf.hover()
end, { desc = "Open diagnostic info" })
