backend = "thumb"
color_space = "lab"
# threshold = 10
palette = "dark"
generation = "interpolate"
check_contrast = true
saturation = 10
alpha = 80

[templates.hypr]
template = 'colors-hypr.conf'
target = '~/.config/hypr/themes/wallust.hypr'

[templates.waybar]
template = 'colors-waybar.css'
target = '~/.config/waybar/themes/wallust.css'

[templates.wlogout]
template = 'colors-wlogout.css'
target = '~/.config/wlogout/themes/wallust.css'

[templates.alacritty]
template = 'colors-alacritty.toml'
target = '~/.config/alacritty/themes/wallust.toml'

[templates.neopywal]
template = 'colors-neopywal.vim'
target = "~/.cache/wallust/colors_neopywal.vim"

[templates.vesktop]
template = 'colors-discord.css'
target = '~/.config/vesktop/themes/wallust.css'
