{...}: {
  services.zapret = {
    enable = true;
    udpSupport = true;
    udpPorts = ["443" "50000:50099"];

    params = [
      # "--dpi-desync=fake"
      # "--dpi-desync-ttl=2"
      # "--orig-ttl=1"
      # "--orig-mod-start=s1"
      # "--orig-mod-cutoff=d1"

      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=badsum"

      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=badseq"
      # "--dpi-desync-fake-tls=0x00000000"
      # "--dpi-desync-fake-tls=!"
      # "--dpi-desync-fake-tls-mod=rnd,rndsni,dupsid"

      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=datanoack"
      # "--dpi-desync-fake-tls=0x00000000"
      # "--dpi-desync-fake-tls=!"
      # "--dpi-desync-fake-tls-mod=rnd,rndsni,dupsid"

      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=md5sig"
      # "--dup=1"
      # "--dup-cutoff=n2"
      # "--dup-fooling=md5sig"

      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=hopbyhop"

      # This one is the most effective
      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=hopbyhop2"
      # "--dpi-desync-fake-tls=0x1603"
      # "--dpi-desync-fake-tls=!+2"
      # "--dpi-desync-fake-tls-mod=rnd,dupsid,rndsni"
      # "--dpi-desync-fake-tcp-mod=seq"

      # "--dpi-desync=fake"
      # "--dpi-desync-ttl=1"
      # "--dpi-desync-autottl=-1"
      # "--orig-ttl=1"
      # "--orig-mod-start=s1"
      # "--orig-mod-cutoff=d1"

      # This one is the most effective, for youtube at least
      # "--dpi-desync=multidisorder"
      # "--dpi-desync-split-pos=1,sniext+1,host+1,midsld-2,midsld,midsld+2,endhost-1"

      # "--dpi-desync=fake"
      # "--dpi-desync-ttl=2"
      # "--orig-ttl=1"
      # "--orig-mod-start=s1"
      # "--orig-mod-cutoff=d1"

      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=badseq"
      # "--dpi-desync-fake-tls=0x00000000"
      # "--dpi-desync-fake-tls=!"
      # "--dpi-desync-fake-tls-mod=rnd,rndsni,dupsid"

      # "--dpi-desync=fake"
      # "--dpi-desync-fooling=datanoack"
      # "--dpi-desync-fake-tls=0x00000000"
      # "--dpi-desync-fake-tls=!"
      # "--dpi-desync-fake-tls-mod=rnd,rndsni,dupsid"

      # "--dpi-desync=fakedsplit"
      # "--dpi-desync-ttl=2"
      # "--orig-ttl=1"
      # "--orig-mod-start=s1"
      # "--orig-mod-cutoff=d1"
      # "--dpi-desync-split-pos=1"

      "--dpi-desync=fakedsplit"
      "--dpi-desync-fooling=badseq"
      "--dpi-desync-split-pos=1"

      # "--filter-tcp=80"
      # "--dpi-desync=fake,split2"
      # "--dpi-desync-autottl=2"
      # "--dpi-desync-fooling=md5sig,badsum"
      # "$hostlist"
      # "--new"
      # "--filter-tcp=443"
      # "$hostlist"
      # "--dpi-desync=fake,split2"
      # "--dpi-desync-repeats=6"
      # "--dpi-desync-fooling=md5sig,badsum"
      # "--dpi-desync-fake-tls=${./tls_clienthello_www_google_com.bin}"
      # "--new"
      # "--filter-tcp=80,443"
      # "--dpi-desync=fake,disorder2"
      # "--dpi-desync-repeats=6"
      # "--dpi-desync-autottl=2"
      # "--dpi-desync-fooling=md5sig,badsum"
      # "$hostlist"
      # "--new"
      # "--filter-udp=50000-50100"
      # "--dpi-desync=fake"
      # "--dpi-desync-any-protocol"
      # "--dpi-desync-fake-quic=0xC30000000108"
      # "--new"
      # "--filter-udp=443"
      # "$hostlist"
      # "--dpi-desync=fake"
      # "--dpi-desync-repeats=6"
      # "--dpi-desync-fake-quic=${./quic_initial_www_google_com.bin}"
      # "--new"
      # "--filter-udp=443"
      # "--dpi-desync=fake"
      # "--dpi-desync-repeats=6"
      # "$hostlist"

      # "--filter-udp=443"
      # "$hostlist"
      # "--dpi-desync=fake"
      # "--dpi-desync-repeats=6"
      # "--dpi-desync-fake-quic=${zaprettdir}/bin/quic_initial_www_google_com.bin"
      # "--new"
      # "--filter-udp=50000-50100"
      # "$ipset"
      # "--dpi-desync=fake"
      # "--dpi-desync-any-protocol"
      # "--dpi-desync-cutoff=d3"
      # "--dpi-desync-repeats=6"
      # "--dpi-desync-fake-quic=${zaprettdir}/bin/quic_initial_www_google_com.bin"
      # "--new"
      # "--filter-tcp=443"
      # "$hostlist"
      # "--dpi-desync=fake,split"
      # "--dpi-desync-autottl=2"
      # "--dpi-desync-repeats=6"
      # "--dpi-desync-fooling=badseq"
      # "--dpi-desync-fake-tls=${zaprettdir}/bin/tls_clienthello_www_google_com.bin"
      # "--new"
    ];

    whitelist = [
      "youtu.be"
      "youtube.com"
      "googlevideo.com"
      "ytimg.com"
      "youtubei.googleapis.com"
      "youtube-ui.l.google.com"
      "youtube.googleapis.com"

      "dis.gd"
      "discord.co"
      "discord.com"
      "discord.design"
      "discord.dev"
      "discord.qgg"
      "discord.qgift"
      "discord.qifts"
      "discord.media"
      "discord.new"
      "discord.store"
      "discord.tools"
      "discordapp.com"
      "discordapp.net"
      "discordmerch.com"
      "discordpartygames.com"
      "discord-activities.com"
      "discordactivities.com"
      "discordsays.com"
      "discordstatus.com"

      "x.com"
      "twitter.com"
      "t.co"
      "twimg.com"

      "medium.com"

      "rutracker.org"
      "rutracker.net"

      "spotify.com"
      "scdn.co"
      "spotifycdn.com"
      "spotifycdn.net"
      "spoti.fi"
      "spotify.link"

      "irc.warframe.com"
    ];
  };
}
