return {
  "folke/ts-comments.nvim",

  enabled = vim.fn.has("nvim-0.10.0") == 1,

  event = "VeryLazy",

  opts = {
    lang = {
      typst = { "// %s", "/* %s */" },
      astro = "<!-- %s -->",
      axaml = "<!-- %s -->",
      blueprint = "// %s",
      c = "// %s",
      c_sharp = "// %s",
      clojure = { ";; %s", "; %s" },
      cpp = "// %s",
      cs_project = "<!-- %s -->",
      cue = "// %s",
      fsharp = "// %s",
      fsharp_project = "<!-- %s -->",
      gleam = "// %s",
      glimmer = "{{! %s }}",
      graphql = "# %s",
      handlebars = "{{! %s }}",
      hcl = "# %s",
      html = "<!-- %s -->",
      hyprlang = "# %s",
      ini = "; %s",
      ipynb = "# %s",
      javascript = {
        "// %s",
        "/* %s */",
        call_expression = "// %s",
        jsx_attribute = "// %s",
        jsx_element = "{/* %s */}",
        jsx_fragment = "{/* %s */}",
        spread_element = "// %s",
        statement_block = "// %s",
      },
      kdl = "// %s",
      php = "// %s",
      rego = "# %s",
      rescript = "// %s",
      rust = { "// %s", "/* %s */" },
      sql = "-- %s",
      styled = "/* %s */",
      svelte = "<!-- %s -->",
      templ = {
        "// %s",
        component_block = "<!-- %s -->",
      },
      terraform = "# %s",
      tsx = {
        "// %s",
        "/* %s */",
        call_expression = "// %s",
        jsx_attribute = "// %s",
        jsx_element = "{/* %s */}",
        jsx_fragment = "{/* %s */}",
        spread_element = "// %s",
        statement_block = "// %s",
      },
      twig = "{# %s #}",
      typescript = { "// %s", "/* %s */" },
      vue = "<!-- %s -->",
      xaml = "<!-- %s -->",
    },
  },
}
